### ISSUE TITLE
farmOS Drupal error installing custom module

### ISSUE THREAD

**Issue by s33a** [s33a/farm_shane_fungi#1]
![custom module error 2](https://user-images.githubusercontent.com/81595892/115159153-97cecf00-a046-11eb-866a-82003081d2e3.png)
Could this have something to do with the namespace path in my PHP file?

I'll play around with it to see what happens unless someone has a definitive answer.

**Comment by s33a** [comment]
![image](https://user-images.githubusercontent.com/81595892/115161211-3102e300-a051-11eb-85f0-ce4ec0b86097.png)
A new error for me trying to install this custom model. Why is my shane_fungi plugin not being recognized?

**Comment by paul121** [comment]
> Why is my shane_fungi plugin not being recognized?

The ID of the plugin in your `@AssetType` annotation does not match the config you provided in `asset.type.shane_fungi.yml`:

https://github.com/s33a/farm_shane_fungi/blob/1aa791309d3f966d8035418b275d6fddaf03e538/farm_shane_fungi/src/Plugin/Asset/AssetType/ShaneFungi.php#L11

The commented lines above the `class ShaneFungi ...` in the `ShaneFungi.php` file are not only comments, but they include an annotation as well. It can be a bit confusing at first to see the annotation included in the comment block but overall it does help keep the code more concise. Annotations are a feature of more "modern" PHP (and other languages!). Drupal 9 was my first time using this feature in a programming language.

Drupal documentation on this: https://api.drupal.org/api/drupal/core%21core.api.php/group/annotation/9.0.x

**Comment by paul121** [comment]
> Could this have something to do with the namespace path in my PHP file?

Re: the `shane_fungi_type` issue, still not sure why this is happening.. can you confirm that this vocabulary was created? It should be listed when you go to `/admin/structure/taxonomy`. If it's not there then the vocabulary isn't being created.. which might give us some clues...

**Comment by mstenta** [comment]
Hi @s33a ! Well done!

- You don't need to nest a `farm_shane_fungi` directory inside the repository's root directory. Doesn't hurt, but it isn't necessary.
- If you plan to have a "Fungi" asset type and a "Fungi types" vocabulary, just like the `farm_fungi` module, then you don't need to recreate those. Just let the `farm_fungi` module provide them, and add `farm_fungi` as a dependency of this module (add `dependencies[] = farm_fungi:farm_fungi` to the bottom of your `*.info.yml` file. Then, this module can just add/extend things rather than duplicate them. This would remove the need for the `config/install/taxonomy.vocabulary.shane_fungi_type.yml` file entirely, which seems to be causing you problems right now (figured I'd suggest that before even trying to figure out why it's causing issues).

That said, doing so would mean this module doesn't actually need to provide *anything*! But that's a good thing, I think.

As I said in [my forum comment](https://farmos.discourse.group/t/approaching-farmos-module-development/762/10):

> it’s always a good idea to start with a plan for your data architecture before you jump into the module code itself. What asset types do you want? What log types? What additional fields are necessary for specific data, or for linking records together? This can all be outlined before you write your first line of code.

Looking at the code you have now, it *seems* like everything is set up correctly. I would wager that you've run into the other thing I described in my forum comment...

> Drupal does a lot of stuff behind the scenes with the information it gets from your module, including creating database tables, generating config entities, caching things, etc. If you are throwing things at the wall to see what sticks it’s possible to end up with a messed up database/cache/etc - and while in theory anything can be detangled, that requires understanding what is tangled in the first place - so it may be easier to just reinstall everything from scratch to make sure you’re starting fresh.

Try reinstalling farmOS from scratch, and then try installing your module. See if you get the same error message. It may just be that things got messed up in the database while you were experimenting.

And definitely definitely get familiar with running the `drush cr` command for rebuilding caches! You can also rebuild caches by going to Admin > Configure > Development > Performance and clicking the button there, but it's possible for the whole frontend to get broken by issues in code and the command line is the only option. Plus `drush` is just awesome once you start using it. :-)

Running `drush` within the Docker container requires a pretty verbose command: `docker exec -it -u www-data farmos_www_1 drush [command]`...

... but you can create a bash alias to make that easier (on Linux/Mac, not sure how on Windows). I have an alias so that I can just run `fdrush [command]` and it will run `drush [command]` inside my farmOS container, just by adding this to my `~/.bash_aliases` file:

```
alias fdrush='sudo docker exec -it -u www-data farmos_www_1 vendor/bin/drush'
```

**Comment by s33a** [comment]
I'll reinstall farmOS from scratch next. Then add the dependency to my info.yml file, and delete the taxonomy.vocabulary.* file. Should I keep the asst.type.shane_fungi.yml file?

My development environment consists of Windows 10 Pro, WSL 2 enabled, Docker Desktop for Windows connected to WSL2, Ubuntu 20.04 LTS on WSL2, and Visual Studio Code with Remote WSL and GitHub extensions. I just used the first Docker Drush command from the documentation from my Ubuntu terminal window and it works just fine.  Thanks for the alias! That will save me a bit of typing.

**Comment by mstenta** [comment]
> Should I keep the asst.type.shane_fungi.yml file?

The `farm_fungi` module already provides a Fungi asset type, so your module doesn't need to. Maybe you'll want to provide additional asset types, though?

**Comment by s33a** [comment]
I will definitely want to add other types of assets. Maybe you can give me some quick advice on how to categorize the following items:

1. Lab 1: Petri dishes, agar media, filled Petri dishes, liquid culture media, liquid culture jars, liquid culture media, culture slants, lab equipment (stir plate, laminar flow hood, HEPA filters, pre-filters, sterilizer, etc.), syringes, syringe caps, syringe needles.
2. Lab 2: grain, sawdust, CaSO4, nutrients, spawn bags, equipment (humidifier, lights, fans, etc.).
3. Growing: grow bags, substrates (we've talked about this before), equipment.

There's quite a bit more to process, but with your guidance, I'll be able to get a good structure down for adding more at a later date.

For my initial testing, I'll work with one category to make sure I've got the process down before adding complexity.

**Comment by mstenta** [comment]
Great info @s33a !

And what do you want your workflow to look like? How granular are you looking to get with each step? Are there certain actions you do/don't want to record in farmOS?

I always try to keep things general, because it means less to maintain. Keeping custom asset and log types to a minimum will make things a LOT easier for you in the long run.

So for example, I'm curious if ALL of the asset types you listed could fit into the existing "Equipment" type, as well as a new "Material" type that we've been talking about adding for a long time.

The idea is: you just have a single "Material" asset type, and you enter each type of material as a single asset, and track inventory for each of them. You could also have multiple assets for each, if you have them in different locations or stocks. For example, if you have 2 buildings that both have "agar media" in stock, you could have two assets: "Agar in building 1" and "Agar in building 2" with an inventory on each, as well as an asset that represents your petri dish inventory. Or even have a separate "Filled petri dishes" asset that you increment the inventory of whenever you fill them with agar. Finally, when you inoculate, you create a Fungi asset, and decrement the inventory of your filled dishes with an input log to the Fungi asset. Just thinking out loud... curious to hear more about your specific workflow and how to model it!

**Comment by s33a** [comment]
I have a Word document that I've been updating from my handwritten notes I can provide to you. Maybe that will help clarify the process and asset/equipment/material types I'll be creating.

I'd put it directly here, but there are a couple of minor ideas I would like to keep between us. It's not proprietary, but why give away the farm? ;)

Should I just message that to you through the forum, or email it?
